config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'

  resources :categories do
    resources :items
  end

  devise_for :users

end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :user
  has_many :items

  paginates_per 3

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  has_many :categories
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all.page(params[:page])
  end

  def show
    @items = @category.items
  end

  def new
    @category = Category.new
  end

  def edit

  end

  def create
    @category = current_user.categories.create(category_params)
    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully edited.'
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path, notice: 'Category was successfully deleted.'
  end

  private
  def set_category
    @category = Category.friendly.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_category, only: [:new, :create, :show, :destroy]

  def index
    @items = Item.all
  end

  def show
  end

  def new
    @item = Item.new
  end

  def edit

  end

  def create
    @item = current_user.items.create(item_params)
    @item.update_attributes(category_id: @category.id)

    if @item.save
      redirect_to @category, notice: 'Item was created successfully.'
    else
      render :new
    end
  end

  def update
    if @item.update(item_params)
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to @category, notice: 'Item was deleted successfully.'
  end

  private
  def set_item
    @item = Item.find(params[:id])
  end

  def set_category
    @category = Category.friendly.find(params[:category_id])
  end

  def item_params
    params.require(:item).permit(:content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
    <% if @category.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@category.errors.count, "error") %> prohibited this topic from being saved:</h2>

          <ul>
            <% @category.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/categories/edit.html.erb
<h1> Edit Category</h1>
<%= render 'form' %>
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1> Category List</h1>
<p> <%= link_to 'New Category', new_category_path %></p>
<hr>
<% @categories.each do |category| %>
    <h3>Category: <%= category.name %></h3><br>
    <p>Creator: <%= category.user.email %></p><br>
    <p>Item list: <%= category.items.map {|i| i.content}.join(', ') %></p>
    <%= link_to 'Show', category_path(category) %>
    <%= link_to 'New Item', new_category_item_path(category) %>
    <%= link_to 'Edit', edit_category_path(category) %>
    <%= link_to 'Destroy', category_path(category), method: :delete %>
    <hr>
<% end %>

<%= paginate @categories %>

app/views/categories/new.html.erb
<h1> New Category </h1>
<%= render 'form' %>
<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<!--<h1> Category <%= @category.name %></h1>-->
<!--Creator: <%= @category.user.email %><br><br>-->
<!--Items: <%= @category.items.map {|i| i.content}.join(', ') %><br>-->
<!--<%= link_to 'Back', categories_path %>-->

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @category.user.email %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %>
<%= link_to 'New item', new_category_item_path(@category) %>
<%= link_to 'Back', categories_path %>


<h1>Listing items</h1>

<table>
  <thead>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @items.each do |item| %>
      <tr>
        <td><%= item.content %></td>
        <td><%= item.user.email %></td>
        <td><%= link_to 'Destroy', category_item_path(@category, item), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
Index

app/views/items/_form.html.erb
<%= form_for(@item, url: category_items_path) do |f| %>
    <% if @item.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@item.errors.count, "error") %> prohibited this topic from being saved:</h2>

          <ul>
            <% @item.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :content %><br>
      <%= f.text_area :content %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/items/edit.html.erb
<h1> Edit Item</h1>
<%= render 'form' %>
<%= link_to 'Back', category_items_path %>

app/views/items/index.html.erb
<h1> Item List</h1>
<hr>
<% @items.each do |item| %>
    <h3>Item Content: <%= item.content %></h3><br>
    <h3>Item Creator: <%= item.user.email %></h3><br>
    itemler gelecek
    <hr>

<% end %>

app/views/items/new.html.erb
<h1> New Category </h1>
<%= render 'form' %>
<%= link_to 'Back', category_items_path %>

app/views/items/show.html.erb
<h1> Category <%= @category.name %></h1>
Creator: <%= @category.user.email %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lyk2015Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p align="right"> Welcome! <%= current_user.email %> </p>

<%= yield %>

</body>
</html>